### ISSUE TITLE
Validating Google Play Receipt

### ISSUE THREAD

**Issue by mhsiddiqui** [dotpot/InAppPy#1]
Google has an [api](https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get) to validate receipt. In InAppPy, for Google play receipt validation, no API call is used. Is it valid method or we should use API for google play case?

**Comment by dotpot** [comment]
Currently this validation is based on PKI signature validation, I'm not familiar that api, I think its purpose is to `Check whether a user's subscription purchase is valid and returns its expiry time.`. This library validates receipts. If you need this functionality PR's welcome ;)
