### ISSUE TITLE
cancelled android purchases do not get caught correctly

### ISSUE THREAD

**Issue by schumannd** [dotpot/InAppPy#26]
in lines 109-110 of googleplay.py:

```
            cancel_reason = int(result.get('cancelReason', 0))
            if cancel_reason != 0:
                raise GoogleError('Subscription is canceled', result)

```

If we look at [the docs](https://developers.google.com/android-publisher/api-ref/purchases/subscriptions) we see that a value of `cancelReason = 0` also indicates cancellation by user. Therefore I do not understand what was the original intention of this snippet of code. If we look at the lines following this snippet:

```
            ms_timestamp = result.get('expiryTimeMillis', 0)
            if self._ms_timestamp_expired(ms_timestamp):
                raise GoogleError('Subscription expired', result)
        else:
            result = self.check_purchase_product(purchase_token, product_sku, service)
            purchase_state = int(result.get('purchaseState', 1))

            if purchase_state != 0:
                raise GoogleError('Purchase cancelled', result)

```

I think the general issue here is, that a subscription can be

a) not cancelled and not expired
b) cancelled and not expired
c) cancelled and expired

So even if we fixed the issue with the code above, we would have to rethink how we throw errors / catch google certificate expiry (see also #25).

I suggest we remove the current mechanism of throwing errors an instead return some sort of datastructure containing: `raw_response`, `is_expired`, `is_cancelled`.

That way we describe all 3 scenarios above. What do you think?

**Comment by dotpot** [comment]
I agree, there are ways of making it better, but since we need to support backwards compatibility I suggest creating maybe `V2` of `GooglePlayVerifier` and maybe `AppStoreValidator` too.

PR's welcome ;)
