### ISSUE TITLE
Please add support for the exclude-old-transactions field

### ISSUE THREAD

**Issue by axper** [dotpot/InAppPy#3]
As Apple docs state https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html we can send the exclude-old-transactions field to only get the latest receipt info. It would be very helpful if you would add support for this field.

Thanks for the great library btw!

**Comment by dotpot** [comment]
Thanks! It would be nice to support this, PR's welcome ;)
