### ISSUE TITLE
ex.raw_response throws exception when apple server is unavailable

### ISSUE THREAD

**Issue by ssuchanowski** [dotpot/InAppPy#46]
Happen to me a couple of weeks ago, request returned 503 code.

Exception:
```
AttributeError: 'InAppPyValidationError' object has no attribute 'raw_response'
```

I think just fixing docs to do a `None` type check before accessing should be sufficient here.

I just want to share this info as apple's in-app purchase servers have a tendency to go south from time to time.

**Comment by dotpot** [comment]
fixed with #51
