### ISSUE TITLE
Be able to grab the vendor user ID

### ISSUE THREAD

**Issue by Natim** [dotpot/InAppPy#47]
With Google we can use the developerPayload to pass an unique identifier so that we can link subscriptions received from Pub/Sub with our vendor User.

With Apple, [it should be possible to grab a applicationUsername](https://stackoverflow.com/questions/29255568/is-there-any-way-to-know-purchase-made-by-which-itunes-account-ios/29280858#29280858) but I couldn't find out how to read that using InAppPy.

**Comment by dotpot** [comment]
@Natim Thanks for contribution. 
Im not sure, maybe you're talking about `shared_secret` ?

Othervise information you're looking might be located in the raw response from apple.

**Comment by Natim** [comment]
Yeah I guess you can't return things that Apple doesn't return via their API.

> You can set stuff on applicationUsername of the SKPayment object that you create, however, it won’t be there on the SKPaymentTransaction.payment once it is returned.
