### ISSUE TITLE
Some query about AppStoreValidator

### ISSUE THREAD

**Issue by burkaslarry** [dotpot/InAppPy#57]
Does this AppStoreValidator validate and verify the IAP receipt  sent from the Apple? If so , Would you please mention where we can get the receiptData ? 

bundle_id = 'com.yourcompany.yourapp'
auto_retry_wrong_env_request=False # if True, automatically query sandbox endpoint if
                                   # validation fails on production endpoint
validator = AppStoreValidator(bundle_id, auto_retry_wrong_env_request=auto_retry_wrong_env_request)

```
try:
    exclude_old_transactions=False # if True, include only the latest renewal transaction
    validation_result = validator.validate('receipt', 'optional-shared-secret', exclude_old_transactions=exclude_old_transactions)
except InAppPyValidationError as ex:
    # handle validation error
    response_from_apple = ex.raw_response  # contains actual response from AppStore service.
    pass
```

Also, does the receipt data setup differ if I use sandbox environment / production environment ? 

I see some uses base64 string of Bundle.main.appStoreURL  for   sandbox production
and hence purchase_token generated by Apple shall not be used at  sandbox production

**Comment by dotpot** [comment]
@burkaslarry Yes it validates receipt. You can find `receipt_info` and other data once you get the [response](https://github.com/dotpot/InAppPy#7-app-store-response-validation_result--raw_response-example).

**Also, does the receipt data setup differ if I use sandbox environment / production environment ?**
Set-up should be the same, but you'll get an error if you'll try to verify sandbox receipt with production env and vice versa (you can auto-overcome that by setting `auto_retry_wrong_env_request=True` so it will automatically switch the environments on those errors). More info is [here](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html) (Table 2-1 Status codes).

Btw this is not an issue with this library, so I'm closing this..
