### ISSUE TITLE
What kind of value I have to use validate method

### ISSUE THREAD

**Issue by SlZeroth** [dotpot/InAppPy#6]
validation_result = validator.validate('receipt', 'signature')

I dont understand signature field

**Comment by dotpot** [comment]
Hey, thanks for the question!

Google Play signs the JSON string that contains the response data for a purchase order. Google Play uses the private key that is associated with your application in the Developer Console to create this signature. [More Info here](https://developer.android.com/google/play/billing/api)

**Comment by dotpot** [comment]
closing now
