### ISSUE TITLE
bundle_id isn't needed for App Store validation

### ISSUE THREAD

**Issue by kpotehin** [dotpot/InAppPy#62]
Hey! `AppStoreValidator` requires `bundle_id` for initialization, however Apple doesn't need it for receipts validation. Can you please delete it?

**Comment by yurabysaha** [comment]
Any new about it ?

**Comment by dotpot** [comment]
@yurabysaha not yet.

**Comment by dotpot** [comment]
@kpotehin @yurabysaha I've added deprecation warning, you will see it in upcoming version. I will fully remove it in version 3, sometime latter. Closing this issue for now.
