### ISSUE TITLE
[FEATURE] Bump up oauth2client dependecy version

### ISSUE THREAD

**Issue by tadeoos** [dotpot/InAppPy#69]
Hey, I'd just want to ask you if you could bump up the `oauth2client` dependency?

I don't think 3.0.0 version is absolutely necessary for this project to work, and with the new `pip` version it's already causing us [`ResolutionImpossible` error](https://pip.pypa.io/en/stable/user_guide/#fixing-conflicting-dependencies)

**Comment by dotpot** [comment]
Yes, we could. Will look into this.
